swcarpentry/python-novice-gapminder

index.md

Cutting:
* lists
* defensive programming
* arrays
Reducing:
* error messages
* reading tabular data
* plotting
* loops
* conditionals
* writing functions
* programming style
* wrap-up

Cutting material based on feedback

---

03-types-conversion.md

This is a multiple choice question with two correct answers. The incorrect choices represent these misconceptions:
- A. correct.
- B. simply wrong arithmetic.
- C. you can't use int() directly on a string.
- D. correct.
- E. adding two variables of type int gives you another int, not a float.
- F. you can't multiply a variable of type str with an int.

Exercise on Arithmetic with Types

---

04-built-in.md
06-libraries.md

Challenge would raise an exception when called. Just adding another value to prevent such.

max was being called on a float (non-iterable)

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/03-types-conversion.md
_episodes/04-built-in.md

An inital go at writing lesson material

First four lessons

---

_episodes/02-variables.md

This change gives an introduction to variables in Python. It is also part of SWC Instructor training.

Adding some content for the variables episode for the new Python lesson

---

_episodes/11-lists.md

Added more content on
* creating lists
* lists having different types of values
* slicing lists (needs more)
* iterating through lists
* dealing with bounds
This is part of my instructor training checkout.

Adding more content to the lists episode.

---

_episodes/15-conditionals.md

As part of my Instructor Training with SWC, I've added more information to the lesson about how to construct if / elif statements. This is generally useful and is also required knowledge for one of the example problems in this lesson.

1June16 - Addition of if / elif syntax to lesson

---

_episodes/01-run-quit.md

Created a challenge question in 01-run-quit.md asking the user to write some code in a code cell and then try converting the entire cell to markdown. For me this was something that I did when I first tried Jupyter to get a feel for switching between the cell types and as an easy method of commenting out experimental code. 
This is for instructor training checkout. @gvwilson

Added a challenge question in 01-run-quit.md

---

_episodes/09-for-loops.md

There was a Python 2 print statement inside the loop explaining the range iterator. Since all other prints are functions, I thought this one should be too.

Fix Python 2 style print statement inside the range for loop

---

_episodes/10-reading-tabular.md

Fixes #36 by adding a challenge to the lesson, asking learners to try using `pandas.to_csv()` to write one of their data frames to a file.

added exercise using pandas.to_csv() to write data to file

---

exercise_avg_gdp_by_decade.md

This is an Instructor Training assignment PR. We guide learners
through a multipart, faded example exercise to design a function
that computes - for a given decade - the average GDP for a
country in its specified continent.

Instructor Training: Added a function exercise

---

_episodes/09-for-loops.md

Created the exercise "Cumulative sum"
Instructor Training Checkout Procedure.

Added exercise in the loop page

---

setup.md

- Restructured in a more natural progressive pattern, from installation of Python, to getting the data, to launching with Jupyter.
- Broken link to gapminder.org fixed.
- A few changes to the actual sentence structure.

Reorganization of setup file

---

_episodes/01-run-quit.md

one small change, this is an update on a previous PR which included more (now irrelevant) changes.

Fixed a missing word

---

_episodes/05-error-messages.md

+ Much work and refinement still needed
+ Described many of the error message types mentioned in the objectives for the lesson
+ Identified missing prerequisite of creating a function definition to understand multi-level tracebacks
+ Identified missing prerequisites for many of the lesson challenges

First draft of lesson 5 "error messages"

---

_episodes/03-types-conversion.md
_episodes/05-error-messages.md
_episodes/10-reading-tabular.md

* Fixed typo in 03-types-conversion.md 
* Added FIXME in 05-error-messages.md
* Added info in the DataFrame.describe() section in 10-reading-tabular.md

fixed a typo and added info

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/03-types-conversion.md
index.md

Only very small changes to actual content

Several minor changes catching typos and cleaning up wording

---

_episodes/21-next-steps.md

I added Pycon in next-steps because it is a "community site for
software, workshops, and help."

Pycon as resource

---

_episodes/12-plotting.md

Add kind='bar' to the data.T.plot() line to make it actually plot a bar plot.

Do a "bar plot" where it says it will

---

_episodes/06-libraries.md

Exercise to test the log function when the input value is outside the range

Add Excercise

---

_episodes/03-types-conversion.md

Closing https://github.com/swcarpentry/python-novice-gapminder/issues/85

Strings to Numbers exercise - output corrected

---

_episodes/05-coffee.md

A suggestion for some questions to reflect over what kind of errors exist, what types are caught by Python, and what can be done to avoid errors.
This should encourage learners to think not only about syntax errors and runtime errors, but also about errors in their own mental models, which are often much harder to correct than errors that are caught by the Python interpreter. Using the Read, Evaluate, Print Loop (REPL) can help spot errors by testing limiting cases.
The idea is to get learners to think about how to prevent errors from occurring in the first place, rather than just fixing them when they do occur. This is the mindset behind defensive programming. Reflecting on this now will prepare learners for the later module on programming style.

Added questions for reflection on morning session during coffee break.

---

_episodes/17-conditionals.md

added parentheses to print statements used to illustrate compound conditionals.

add parentheses to print statement

---

_episodes/14-writing-functions.md

I think this could be a good exercise to include for functions and return variables.  If does use if-blocks though, so maybe it would be appropriate for the later episode.

Here's a new exercise for function encapsulation

---

_episodes/02-variables.md

Change under discussion in  #114: 
- Change variable names in swap exercise
- Add solution to swap exercise

Switch variable names and add solution in swap exercise.

---

_episodes/06-libraries.md

Added a solution to the question on the origin of `sqrt(x)` vs `pow(x,y)`. 
Maybe too much extra detail in the second part of the answer?

Add solution for Exploring the Math Library

---

_episodes/06-libraries.md

- Add answers to challenge questions and code for solution. 
- Fixed formatting of code in question.

Add example to Locating the Right Library

---

_episodes/06-libraries.md

Expanded on the bases="AGTC..." example to have learners create a program that prints out a random base from the string.  Learners are given a jumble of statements, without temporary variable assignment, which can be rearranged to form a solution.  Not all provided statements are necessary.

Added jigsaw puzzle programming problem to examples

---

_episodes/18-style.md

First PR as part of instructor training checkout procedure.
Assertions could get a much longer treatment but I have tried to mirror the fairly terse character of the rest of the lesson.
Reference:
https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
https://wiki.python.org/moin/UsingAssertionsEffectively

18-style.md : replace "FIXME" with a brief description of the assert statement

---

_episodes/01-run-quit.md

Clarified initial Jupyter description and added assessment

First section and assessment

---

_episodes/06-libraries.md

Added a matching problem for python library calls.

matching exercise for library calls

---

_episodes/13-looping-data-sets.md

I am submitting this pull request as part of my instructor training checkout.

Added solution to problem 1 and 2 in lesson 13 (Looping Over Data Sets) 

---

_episodes/01-run-quit.md
_episodes/02-variables.md

As part of instructor training checkout:
* Added in challenge solutions to episode-1
* Addressed #134 and added description of string in episode-2

Updated episode 1 and fixed #134

---

_episodes/02-variables.md

Also change variable name "element" to "atom_name", as the word "element" is used nearby in another context. See also PR #139 - we may wish to merge in #139 before this one. I'm happy to resolve any conflicts.

Say a little more about substrings, slicing, and so on

---

_episodes/02-variables.md

The lesson says that you can add values to 'print', but it doesn't explain the difference between printing a string and printing a variable. This may be confusing to beginners as some of those are assigned values and others are contextual strings.

clarification on passing string as argument

---

_episodes/03-types-conversion.md

- first cut at complete solutions for episode with some minor suggested edits to text
- we could also replace `print(type(foo))` with just `type(foo)` since python will print out the string representation of the returned result if you are following along in the REPL. 
- closes #121

provide solutions to data types and conversion

---

_episodes/07-reading-tabular.md

I have written solutions to episode 7 as per #126 .
This is my 1st contribution to swcarpentry, I welcome all critical feedback and will be able to edit accordingly. 
An issue I had: in line 292 of _episodes/07-reading-tabular.md, my attempt at enumeration didn't work. I tried to figure it out and could not! Any suggestions?

Ep 7 solns

---

_episodes/11-lists.md

Added very brief mention of '.extend' after the '.append' example in episode 11 on LISTS. Repetition of concept combined with a very intuitive extension of append command might help students internalize the idea of modifying lists.

Instructor training. See description for details.

---

_episodes/13-looping-data-sets.md

The description of the glob library sounded somewhat strange to me so I updated it. I did this also to complete the checkout procedures for a software carpentry instructor training course.

changed wording of episode 13 glob description

---

CONDUCT.md

A few changes on style.
Need manual changes at CONTRIBUTING.md!

Update style to v9.2.4 to restore CONDUCT.md

---

CONTRIBUTING.md

My email address for instructor training is greg.woodward@kc.frbres.org

Updated links in the document to replace FIXME's with correct links

---

_episodes/11-lists.md

Add missing line to fix style

---

_episodes/02-variables.md

The challenge suggest a table so I included a text like table as comment.

Improve Swapping Values Challenge

---

_episodes/02-variables.md

We have a section called "Use a slice to get a substring." which make the FIXME out of date.

Remove out of date FIXME

---

_episodes/02-variables.md

To fix
in http://swcarpentry.github.io/python-novice-gapminder/02-variables/.

Add missing line

---

_episodes/02-variables.md

> Indices are numbered from 0
is a complete statement. We don't need to complicate it.

Simplify statement

---

_episodes/02-variables.md
_episodes/11-lists.md

because we already use can't in many other part of the text.
I used
~~~
$ cd _episodes
$ for i in *; do sed -i "s/cannot/can't/g" $i; done
~~~

Use can't instead of cannot

---

_episodes/02-variables.md

This pull request fixes #189 Missing solution for Predicting Values Challenge

Add solution to "Predicting Values" exercise

---

_episodes/01-run-quit.md

Change all the non-caps instances of `control` mode for `command` mode.

Change all instances of control mode to command mode in e01.

---

_episodes/14-writing-functions.md

This is my first contribution.  Feedback would be most appreciated!

exercise walking learners through process of simulating a dynamical system

---

_episodes/12-for-loops.md

A solution is added for each of the challenge questions in the lesson.
Fixes #203

Add solutions to For Loops lesson

---

_episodes/04-built-in.md

Fixes #193, fixes #194, and fixes #195

Add solutions to Built in Functions

---

_episodes/06-libraries.md

Add missing solution for There Are Many Ways To Import Libraries! challenge, see issue #197.
This is for instructor training checkout.

Add solution to "import libraries" challenge #197

---

_episodes/08-data-frames.md
_episodes/13-looping-data-sets.md

Added import pandas to episodes 08 and 13 for consistency throughout episodes. This pull request is for instructor checkout.
Fixes https://github.com/swcarpentry/python-novice-gapminder/issues/209

Added import pandas to lessons

---

_episodes/01-run-quit.md
_episodes/08-data-frames.md

Add solutions to the first three exercises in episode 08. 
Also, add the undo-cell-deletion option "Z" to episode 01, along with minor formatting fixes

add solutions to pandas exercises 

---

CONTRIBUTING.md
_episodes/01-run-quit.md
_episodes/03-types-conversion.md
_extras/design.md

Hi 
I found some typos in the material and I also propose some minor word changes. The most substancial change is the proposed solution to an exercise on the Episode: Data Types and Type Conversion. I believe the current solution asks knowledge of a piece of math that won't be tangible to the audience of SC at large. I propose another solution that gives the same result but is more intuitive for the audience and make the concept more clear. 
José

Contribution for Software Carpentry Checkout

---

_episodes/03-types-conversion.md

Add solution for Choose a Type challenge

---

_episodes/18-style.md

At the beginning, add some words about the importance of styling.
Also propose the reading of Google style guide.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson …

Add section about importance of coding style

---

_episodes/08-data-frames.md

A small note at the beginning about what are DataFrames (and Series) seemed necessary.
Please delete the text below before submitting your contribution.

Add a section introducing Pandas DF/Series

---

_episodes/14-writing-functions.md

Added a challenge in which a function is called before it is defined to illustrate that order of operations also means defining functions before using them.

Added an additional challenge to order of operations challenge 

---

_episodes/08-data-frames.md

An example of grouping and aggregating on dataframe.
This should touch issue #210

Add a select-apply-combine section

---

_episodes/04-built-in.md

The list of answers was not rendered as list

Fix fomatting of solution

---

_episodes/03-types-conversion.md

This is part of my instructor checkout procedure.
Add missing part 6 solution to 'Choose a Type' exercise.
Fixes #254

Add missing example solution 6

---

_episodes/09-plotting.md

add external links to matplotlib and pandas

---

_episodes/03-types-conversion.md

Addresses #190.
I tried to clean up the language based on the suggestion in #190, but with a bit more description.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson …

Fix int/float language in 03-types-conversion.md

---

_episodes/02-variables.md

- as suggested by @rgaiacs in #181

adopt a whitelist approach to variable naming

---

_episodes/03-types-conversion.md

Modified code to reflect error in "Cannot add numbers and strings"

harmonize example code to reflect the error shown

---

_episodes/11-lists.md

This PR adds solutions to all challenges in episode 11.  I also fixed a display problem.
This is a PR for instructor training checkout.

Lists solutions

---

_episodes/07-reading-tabular.md

The commit message says it all.

07, Reading tabular data: Fix typo

---

_episodes/06-libraries.md

The commit message says it all.

06, Libraries: Fix typo

---

_episodes/02-variables.md

`str(a)[1]` would allow to get the second digit, but that is not what the question aims at, so I add the code people are expected to try.

02, Challenge: Use more exact wording

---

_episodes/09-plotting.md

The commit message says it all.

09, Plotting: Typo

---

_episodes/12-for-loops.md

The `append()` method of lists was already introduced, so I think it's best to use it as well.

12, for-loops: Typo and Cognitive Load Reduction

---

_episodes/08-data-frames.md

Fix some typos and also add more explanations to make the content easier to understand.
Please have a closer look at bf4b62b.

08, Dataframes: Typos and Explanations

---

_episodes/06-libraries.md

there was an error in the solution to "Locating the right module". fixes #278

fix error in solution in episode 6

---

_episodes/13-looping-data-sets.md

Since regular expressions are not necessarily introduced and globs are not real regular expressions as far as I understand it, I stick to the term used throughout the rest.
Also, I fixed a bug in a challenge (b4419cc) that made the solution always return 0.

13, looping data-sets: Terminology & Bugfix

---

_episodes/18-style.md

add one solution and fix an existing solution which had typos and assumed python script (`import sys; n = sys.argv[1]; ...`)

add solutions to episode 18 and fix existing solution

---

_episodes/14-writing-functions.md

this adds new solutions to all exercises in episode 14 except one, and corrects the only pre-existing solution to the last exercise since it had typos, incorrect name of imported pandas library, and used the deprecated `.ix[]` method

add solutions to exercises in episode 14

---

_episodes/17-conditionals.md

all missing solutions in episode 17

add solutions to episode 17

---

_episodes/02-variables.md

Based on the suggestion in #183 here is a quick change to implement that suggestion.

noting that double quotations are fine too

---

_episodes/02-variables.md

- thanks for the report, @mbonsma!
- closes #298

fix broken link to error messages

---

_episodes/06-libraries.md

I opted to reduce the complexity of the task to to reorder and fill in the blank only to focus the reasoning on the flow of solving the problem, instead of having also delete lines.  I also made fill in

simplify exercise on parson problem and add solution, fixes #288

---

_episodes/09-plotting.md

This is a minor contribution reordering some bits of the plotting episode so as not to mention for loops or lists, which are in a subsequent episode.

removed for loop and lists from plotting section

---

_episodes/06-libraries.md

This solution doesn't introduce new functions to students and also
solves the problem in a more straightforward way.

Made parson's problem less confusing

---

_episodes/06-libraries.md

A few more edits to lesson 6's jigsaw puzzle after more discussion, fixes #309

Lesson 6 Jigsaw Puzzle edits

---

_episodes/06-libraries.md

Issue #311 points out that one of the examples in this lesson uses an
inconsistent style with other examples. The necessary change is to add
underscores in the example to indicate where students should add code.

Small Modification to Example in Lesson 6

---

_episodes/02-variables.md
_episodes/03-types-conversion.md
_episodes/04-built-in.md

Changed "quotation" to "quote" in three files to make the episode consistently use the shorter phrase, all based on open issue #191.
I welcome feedback!

fix for issue 191: changed 'quotation'(s) to 'quote'(s) for consistency

---

_episodes/03-types-conversion.md

The choose a type challenge has pretty ambiguous questions and answers. This PR aims to clarify some of them.
proposed answers are:
- for #2 I’ve specified units in days, forcing the choice of ‘floating point number’
- for #3 I’ve added that string or integer are fine depending on type of serial number
- removed #4 entirely because what is the age of a lab specimen? I’m sure 1000 labs have 1001 ways of measuring that
- for #5 (new #4), specified in the answer that float or integer are fine depending on units
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your …

Clarifying the ‘choose a type' challenge

---

_episodes/01-run-quit.md

Changed verbiage in http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/

Verbiage re Jupyter Notebooks Issue #175

---

_episodes/09-plotting.md

Proposition that adresses issue #325, suggested by @gaurav. Is this what you had in mind? Feel free to comment, update. I made it as a callout box in the end.
Regards,
Olav

include savefig

---

_episodes/03-types-conversion.md

Since some people may still be using Python 2, and this particular weirdness caused me a lot of grief early in my coding career.

Add note about Python 2 integer division

---

setup.md

There is a new website for Anaconda.

Fixed links to Anaconda download pages

---

_episodes/08-data-frames.md

I think the dir function/command is very useful for finding out what functions are available for a given data object.  Given that this is an optional side-project, I included an introduction to the topic as a challenge.
Note, I totally waved my hands and glossed over the "double underscore" data/functions that dir returns.  Someone with more expertise in python should (1) fix my terminology and (2) decide what level of description is necessary for those components.
further modifications (PR's) on this are requested!

add challenge that introduces the dir command

---

_episodes/14-writing-functions.md

The function iterate is not working, because of an IndexError. I propose the following solution using append.

Fixed solution of "Simulating a dynamical system"

---

_episodes/02-variables.md

episode 02 cleanup

---

_episodes/01-run-quit.md

minor correction in 01-run-quit.md

---

_episodes/08-data-frames.md

variable renamed to be consistent with previous exercise

variable data renamed to df in 08-data-frames.md

---

_extras/guide.md

correction in guide.md

---

_episodes/18-style.md

The `average` program was calling itself, and should have sum/len.

Average program should have a divide by count

---

_episodes/09-plotting.md

Adding a description of how legends work to the plotting lesson.

add legend description

---

_episodes/06-libraries.md

"be written" instead of "bewritten"
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, …

Fixed a typo

---

reference.md

I added all commands used and definitions for relevant terminology to the references.md page.

Added references and definitions to reference.md

---

_episodes/09-plotting.md

Pull request for https://github.com/swcarpentry/python-novice-gapminder/issues/365

Add commentary for making accessible plots

---

_episodes/10-lunch.md

Added a first draft of three lunch time reflections modeled off of the morning coffee break reflections.
My intention was to get them thinking about what sort of packages they might find useful and that using a package can be much easier than writing all the code themselves. The second was to get them thinking about tidy data concepts and how they would have to have things to be machine readable. The third is to hint at things like loops and conditionals that are necessary to handle large and/or complex tasks.

Lunch reflection goals first draft

---

_episodes/14-writing-functions.md

Exercise was not properly rendered because it was missing

Add missing '{: .challenge}'

---

_episodes/09-plotting.md

Import Pandas as pd in lesson 09, plotting

---

_episodes/13-looping-data-sets.md

Import Pandas as pd in lesson 13, looping data sets

---

_episodes/14-writing-functions.md

Import Pandas as pd in lesson 14, writing functions

---

reference.md

- also applying here for consistency, seems to be the last place we are doing a bare `import pandas`
- closes #382

switch to import pandas as pd

---

setup.md

Included instructions for Mac and Windows users on accessing the command line.
Since the intention of this lesson is to use Jupyter Notebook, I would omit instructions on launching without the notebook.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time …

Updated Jupyter launch instructions (command line)

---

_episodes/09-plotting.md

09-plotting.md: fix typos

---

_episodes/15-scope.md

15-scope.md: fix typo

---

_episodes/01-run-quit.md
_episodes/03-types-conversion.md

Nothing major, identified during teaching this course

Some small typos

---

_episodes/04-built-in.md
_episodes/07-reading-tabular.md
_episodes/11-lists.md
setup.md

update links in setup.md and fix broken links

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/03-types-conversion.md
_episodes/04-built-in.md
_episodes/06-libraries.md
_episodes/08-data-frames.md
_episodes/11-lists.md
_episodes/12-for-loops.md
_episodes/13-looping-data-sets.md
_episodes/16-coffee.md
_episodes/19-wrap.md

This PR is a work in progress to accumulate incoming changes for #393
Will be systematically going through lessons to make sure code samples + output are correct and links are correct. Commits from other maintainers are welcome! @souravsingh @ntmoore @vahtras

wip: lesson release changes

---

reference.md

Use proper syntax for Python code blocks.

reference.md: fix code blocks

---

README.md
environment.yml

This PR add necessary files to the `binder` branch of the `python-novice-gapminder` lessons. Will open a separate PR to add the Binder button to the main `README.md`.

Add necessary files to the binder branch

---

README.md

This PR adds only the binder button.

added binder button

---

_episodes/02-variables.md

In line 291, the solution should be 2 and not 1.

updated solution for string conversion

---

_episodes/13-looping-data-sets.md

Changing rpartition to split

---

_episodes/12-for-loops.md

I appreciate this is quite minor stuff but i've added some spaces in sections of this lesson for style consistency.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …

added spaces in line with PEP8 and for consistency

---

_episodes/18-style.md

Feel free to ignore this PR but when I think "online" I think looking it up on the internet.  Since this goes along with the function you just created, perhaps "inline" would be better?

Online to inline help

---

setup.md

In installation instructions for Mac OS X, point 3, suggest to install in home directory rather than root directory. I have seen so many problems created by installing in root directory. I am not familiar with Windows, but can assume similar recommendations should be made.

Mac_installation_update.md

---

_episodes/02-variables.md
package-lock.json

---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …

 Instructor-training assignment variables names are case sensitive

---

_episodes/08-data-frames.md

See diff & https://medium.com/dunder-data/minimally-sufficient-pandas-a8e67f2a2428#46f9 ;-)

Discourage df.column syntax

---

_episodes/18-style.md

Companion to https://github.com/swcarpentry/git-novice/pull/698. Please find context & discussion there.

Harmonise code style mentions for PEP8 & Google's guide

---

_episodes/18-style.md

#458  
Loop was refactored, variable name improved and adjusted to PEP8.  This is my first pull request in both github and this project, as part of instructor checkout.  Please advise if something has been done incorrectly.  I made these changes after seeing the thread at: https://github.com/swcarpentry/python-novice-gapminder/issues/458
Thanks.

Swcarpentry#458 nsf

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/03-types-conversion.md
_episodes/06-libraries.md
_episodes/07-reading-tabular.md
_episodes/08-data-frames.md
_episodes/09-plotting.md

The `po` files are the tokenised version of the lessons. The [tool we are using](https://github.com/carpentries-i18n/po4gitbook) complains if the following *typos* or empty lines at the end of sections are not fixed.

[translations] Clean lessons to create po files

---

.travis.yml
_episodes/16-writing-functions.md

The logistic map can be quite confusing when first introduced, and the goal of this problem is to practice writing functions, not to stress out the learners with new math concepts. These changes introduce the logistic map equation (which had been hidden in the "solution" area), describe what it does, and rename several variables to be less abstract. This better-grounded version of the problem statement ought to be more accessible. A print statement has also been added, with representative output, that demonstrates the utility of the logistic map, just for good measure.
These changes are not expected to break anything, but the code in PR #344 may be in conflict.

Rephrased dynamical model problem to be more accessible

---

_episodes/11-lists.md

This deals with #468 as part of my instructor training checkout process
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to …

do not add 9 to list of primes

---

_episodes/11-lists.md

The code cell and output are out of sync.
The last line also includes quotes which doesn't happen when using print()
Credit to @tobyhodges for bumping into it during a course.

Correct exercise output

---

_episodes/18-style.md

These bullet points were not really appropriately positioned as such. It is my opinion that they flow better as sentences in a paragraph (much like the previous section).
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve …

Two bullet points became a short paragraph

---

_episodes/01-run-quit.md

Replace "wither" for "either".

Fix typo on Episode 01

---

_episodes/12-for-loops.md

Improve the explanation of the solution for the "Identifying Variable
Name Errors" exercise in the For Loops episode (12). Rearrange the
expected errors to mimic the order in which they they would appear as we
solve them. Add missing expected error for undefined variable `a`.

Improve solution to exercise in For Loop episode

---

_episodes/12-for-loops.md

As "sum" is a built-in function, it is better to name this variable something different.

Change the variable name "sum" to "summatory"

---

_episodes/08-data-frames.md

This command was already executed and it is unnecessary to run it again.

Remove duplicate line

---

_episodes/02-variables.md

This PR indents code block in the list in the "Use variables to store values" section so that it appears in line with the bullet point it belongs to:
<details><summary>Screenshot</summary>
</details>

02-variables.md: indent code block

---

_episodes/01-run-quit.md

This PR fixes the setup link in the first episode.

01-run-quit.md: Fix setup link

---

_episodes/04-built-in.md
_episodes/08-data-frames.md

Use proper HTML tag for keyboard shortcuts in two episodes.

Use HTML 'kbd' tag for keyboard keys

---

_episodes/11-lists.md

Well, a parenthesis is missing...

11-lists: add missing parenthesis

---

_episodes/04-built-in.md

Now it is fixed
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please …

Output of print(my_string.swapcase()) was missing

---

_episodes/03-types-conversion.md
_episodes/06-libraries.md
_episodes/07-reading-tabular.md
_episodes/08-data-frames.md
_episodes/09-plotting.md
_episodes/11-lists.md
_episodes/12-for-loops.md
_episodes/13-conditionals.md
_episodes/14-looping-data-sets.md
_episodes/15-coffee.md
_episodes/16-writing-functions.md
_episodes/17-scope.md

Hi,
I'm reviewing the challenges for this lesson and making some minor improvements. Please let me know if I should create a separate issue to discuss this.
Episodes reviewed so far:
I hope these changes are helpful for the lesson.
Best wishes,
V

Challenges review

---

_episodes/01-run-quit.md

Hi,
please see #504 for discussion.
If merged, this PR will:
- Modify 'Kernel' item in list of Menus.
- Add 'Kernels' callout block explaining what is a kernel and adding link to Jupyter Documentation.
Best,
V

_episodes/01-run-quit.md: Add 'Kernels' callout block.

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/03-types-conversion.md
_episodes/06-libraries.md
_episodes/07-reading-tabular.md
_episodes/08-data-frames.md
_episodes/09-plotting.md
_episodes/11-lists.md
_episodes/12-for-loops.md
_episodes/13-conditionals.md
_episodes/14-looping-data-sets.md
_episodes/15-coffee.md
_episodes/16-writing-functions.md
_episodes/17-scope.md

This is an attempt at starting to work on the `narrative` branch (see discussion on #463).
If merged, this PR will:
- merge latest changes from `gh-pages` branch.
- Edit Episode 02 according to the lesson story line (8acfda0)
For future PRs to this branch, is it okay to bring the latest changes from `gh-pages` every time, or should I avoid this?
Thank you for any assistance you can provide,
Vini

Merge changes to gh-pages and edit Episode 02

---

_episodes/02-variables.md

- Switch examples to use country names.
- refs #463

update episode with overarching lesson theme

---

_episodes/01-run-quit.md

As noted in #539 - moves justification for using JupyterLab and an explanation of alternative methods of running python scripts to the start of the lesson

Explain alternative python script execution methods earlier in lesson

---

_episodes/14-writing-functions.md

Per suggestions, I revised the problem to NOT use the numpy arange() function.  This is a little more clunky, but it does work and fits within the introduced tools

removed numpy reference

---

_episodes/08-data-frames.md

There's a small typo in the variable name
Changed dir(myString) to dir(my_string)

fixed an inconsistent variable name

---

_episodes/01-run-quit.md

<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …

remove duplicate word

---

_episodes/13-conditionals.md

This PR seeks to improve three aspects of the solution to the "Initializing" challenge in episode 13.
1. The solution includes the expression `== None`, which is contrary to PEP8 and thus widely frowned on. This PR changes it to `is None`, but because no-one would expect a learner to know about this, it includes a note of explanation.
2. I find the statement "the `values` list is iterated three times" rather confusing, since `values` is only iterated once: the inner loops iterate over exactly two values each, not the whole list. (Each member of `values` appears in three loops, but that is not the same thing as the entire list being iterated three times.) I have suggested alternative wording.
3. I have performed some tests and found that the second solution is not, in fact, the most …

Improve the solution to "Initializing" (Ep. 13)

---

_episodes/02-variables.md

Hi,
Here are some minor fixes. If merged, this PR will:
- Close slice with bracket rather than parenthesis in descriptive text
- Add print statement to solution of 'Predicting Values' challenge
- Fix punctuation of 'Slicing Concepts' challenge
Best,
Vini

Ep02 minor fixes/typos

---

_episodes/06-libraries.md

Updated version of #586 using a separate branch.

Adding random.choice as a sampling example

---

_episodes/16-writing-functions.md

suggested by @fercer in issue #588
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
instructor.training@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The …

Added more print statements to greeting function

---

_episodes/02-variables.md

Add alt text developed by Owen McGrath for https://swcarpentry.github.io/python-novice-gapminder//fig/2_indexing.svg

Add alt text

---

_episodes/01-run-quit.md
_episodes/02-variables.md
_episodes/09-plotting.md
index.md

replace relative links

---

_episodes/01-run-quit.md

this PR builds on #593 as it was based off the fork's `gh-pages` instead of a new feature branch
closes #591

update IDE discussion in initial setup

---

index.md
links.md

fix: broken links

---

episodes/08-data-frames.md

This code snippet often causes a lot of confusion for the participants.

Instructor notes for the split-apply-combine exercise.

---

episodes/11-lists.md

Remove reference to 'two dimensional lists'

---

episodes/08-data-frames.md

fix: correct challenge formatting

---

episodes/09-plotting.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Improved alt text for Image 1, line 41 as part of the Alt-Text and the Workbench Skill-Up Session with @tobyhodges 
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your …

Edited Alt Text proposal for line 41
