swcarpentry/python-novice-gapminder

- _episodes/09-data-frames.md
This is an instructor training PR that adds a simple exercise to the 09-data-frames episode.  I chose to make the csv loading a little more complicated than the minimal command (using the `index_col` argument) in order to allow the difference between `df.loc` and `df.iloc` to surface in the classroom, but I understand if there is a preference for simplicity at this point.
> ENH: add individual val select ex to 09-data-frames episode

- _episodes/04-built-in.md
- _episodes/05-error-messages.md
- _episodes/06-libraries.md
- _episodes/11-data-frames.md
- _episodes/15-conditionals.md
- _episodes/16-writing-functions.md
- _episodes/19-defensive.md
- _episodes/21-next-steps.md
Fixed a couple of typos. The `3.0` to `3.54` change is important.
The `FIXME` in the `kelvin_to_celsius` function was replaced by the actual calculation.
I kept each fix in a single commit so you can cherry pick but I can also stash them if desired.
> Fix some typos

- README.md
- _episodes/01-run-quit.md
- _episodes/05-error-messages.md
- _episodes/06-libraries.md
- _episodes/10-reading-tabular.md
- _episodes/11-data-frames.md
- _episodes/13-looping-data-sets.md
- _episodes/19-defensive.md
- _episodes/20-style.md
- _extras/design.md
- _extras/guide.md
- setup.md
When running the lesson check previously many warnings were displayed. This commit has various changes the the markdown files to remove all but one of these warnings. This was done as a part of the instructor-training assignment.
Previous warnings:
./README.md: Line(s) are too long: 5
./_episodes/01-run-quit.md: Line(s) are too long: 21, 23, 29, 45, 46, 47, 48, 49, 57, 67, 72, 75, 80, 85, 91, 96, 98, 99, 100
./_episodes/05-error-messages.md: Line(s) are too long: 109, 113, 174
./_episodes/06-libraries.md: Line(s) are too long: 48
./_episodes/11-data-frames.md: Line(s) are too long: 275
./_episodes/13-looping-data-sets.md: Line(s) are too long: 57
./_episodes/19-defensive.md: Line(s) are too long: 149
./_episodes/20-style.md: Line(s) are too long: 31, 190
./_extras/design.md: Line(s) are …
> Fixing various warnings produced by 'make lesson-check-all'

- _episodes/02-variables.md
Changed nomenclature in the same paragraph from low/high to start/stop because for novices
it could get confusing with the upper- and lower-case explanation that follow directly after.
> Added an introductory bullet point to 'Use a slice to get a substring'.

- _episodes/07-reading-tabular.md
- _episodes/08-data-frames.md
- _episodes/09-plotting.md
- _episodes/17-conditionals.md
- _extras/design.md
The Pandas Python library uses the term "dataframe" without a space rather than "data frame".  For example, see the Pandas documentation describing a dataframe [here](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe).  This commit changes all instances of "data frame" (including camelcase versions) to their matching case without the middle space.
> all cases of "data frame" (with space) moved to "dataframe" (without space)

- _episodes/17-conditionals.md
The variable `mass` is replaced with `m` in the appropriate loops.
> Fix incorrect variable names in conditionals lesson

- _episodes/08-data-frames.md
In the "Selecting Indices" exercise from Episode 8 `pandas.load_csv()` appears to be a typo for `pandas.read_csv()`
> pandas.load_csv() typo in Episode 8 exercise

- _episodes/02-variables.md
Would including math "interval" notation of "[" as inclusive, ")" as exclusive help with defining the behavior of slices?  Modification proposed.
> modified slice description

- _episodes/01-run-quit.md
This is part of the checkout process for Jake Szamosi. Adding instructions for using indents to create sublists in Markdown.
> Add instructions for sublists

- _episodes/17-conditionals.md
Soften the wording regarding the else statement.
This is a pedantic change, but the else statement is not always attached to an if statement. It can for example be used in a try/except clause:
https://docs.python.org/3/tutorial/errors.html
```
for arg in sys.argv[1:]:
try:
f = open(arg, 'r')
except OSError:
print('cannot open', arg)
else:
print(arg, 'has', len(f.readlines()), 'lines')
f.close()
```
> Update wording in 17-conditionals.md

- _episodes/12-for-loops.md
Hi folks,
The only function the students have been taught that accumulates values in a list is `append()`, but it does not return a value, so the line:
```
> # List of word lengths: ["red", "green", "blue"] => [3, 5, 4]
> lengths = ____
> for word in ["red", "green", "blue"]:
>     lengths  = lengths.____(____)
> print(lengths)
> ~~~
```
will fail.  This can be done by using the `__add__()` function, but I'm pretty sure this isn't what the problem set designers had in mind.
> fixed faulty "Practice accumulating" problem set

- _episodes/04-built-in.md
Add easy_string to clarify that max works on iterables.
When the iterable is a string, python orders the characters in
lexicographical order.
> Clarify 04-built-in:Spot the difference exercise

- _episodes/01-run-quit.md
When typing H in Command mode in jupyter version 4.3, the two columns
refer to:
Command Mode and Edit Mode
It could be confusing name it Control here.
> E01: Change Control mode for Command mode.

- _episodes/03-types-conversion.md
I think is it worth warning about it, even if the teacher may choose to skip it.
Also some people might not be aware of running python2 interpreter, and
this can be confusing.
> Update E03: warn about `/` operator between integers in python2.

- _episodes/03-types-conversion.md
This is a PR for instructor training checkout.
I suggest this is a better solution to the challenge in that it actually gives the correct answer to the question posed, with the additional merit of using only Python constructs that have been introduced at this point in the lesson. For the values given in the original solution, the correct answer is 15 surveys to reach everyone once, not 14.
The original solution only works when num_per_survey exactly divides num_subjects, and although there is acknowledgement of this limitation in the suggestion to calculate the remainder and test if it's non-zero, this is not implemented in the solution and indeed conditionals are not introduced until much later in episode 17.
A possible objection to my solution is that it requires mathematical knowledge …
> Alternate solution to Division Types challenge

- _episodes/07-reading-tabular.md
Pandas (describe) does not do statistics, it gives us the basic numbers and helps us to work the others out (through `apply`, `groupby`, `aggregate`, etc).
Also added the information of `include='all'` when `describe`ing the DataFrame, since it will be useful for when non-numerical data is in place.
> Adjust the meaning the keypoint about statistics

- _episodes/11-lists.md
A misplaced `{: .python}` threw off all following python code an output formatting
> Misplaced {: .python}

- _episodes/14-writing-functions.md
Added a solution to 'Definition and Use' from lesson 14-writing-functions.
Explained that a function call always needs parenthesis, otherwise a memory address of the function object is given.
Part of instructor checkout.
> Davidmatten

- _episodes/09-plotting.md
The read_csv calls omitted the 'data/' prefix from the paths to the csv files resulting in an error. Added the 'data/' prefix to the calls in the Correlations and More Correlations exercises.
This PR fixes #244
> Fix file paths in read_csv calls

- _episodes/08-data-frames.md
- _episodes/12-for-loops.md
- _episodes/14-writing-functions.md
Some exercise solutions (in episodes 08, 12 and 14) were not being
formatted as solutions correctly, due to various typos in the closing
solution tag. Additionally the table in the solution in episode 12
needed a preceding empty line to be formatted as a table.
> Fix formatting of several solutions

- _episodes/13-looping-data-sets.md
- limit glob pattern to gapminder CSVs with a gdpPercap_1952 field
- fixes #131
> make glob more specific

- _episodes/02-variables.md
This updates the text for the 'Variables Persist Between Cells' callout to hopefully make it clearer and more understandable. 
Fixes #184
> Update text for explaining variable persistancy in cells

- _episodes/02-variables.md
An additional challenge question related to array slicing which explores what happens when an upper index out-of-range is used. It is helpful to know that no error is thrown, but behaviour may not be as expected.
> Array slicing - out-of-range upper index

- _episodes/01-run-quit.md
- there are a few python snippets however, updated them to `.language-python` ala #312
- fix typo
- closes #314
> remove .python class from markdown snippets

- .gitignore
- CODE_OF_CONDUCT.md
- Makefile
- _config.yml
- _includes/lesson_footer.html
- _includes/links.md
- _includes/navbar.html
- bin/boilerplate/CODE_OF_CONDUCT.md
- bin/boilerplate/CONTRIBUTING.md
- bin/boilerplate/_config.yml
- bin/boilerplate/_episodes/01-introduction.md
- bin/boilerplate/_extras/about.md
- bin/boilerplate/_extras/discuss.md
- bin/boilerplate/_extras/figures.md
- bin/boilerplate/_extras/guide.md
- bin/boilerplate/index.md
- bin/boilerplate/reference.md
- bin/boilerplate/setup.md
- bin/lesson_check.py
- bin/lesson_initialize.py
This pull request brings the latest version of the template to this repository. Release notes are available from the styles GitHub Repository. See [v9.5.1](https://github.com/carpentries/styles/releases/tag/v9.5.1) and [v9.5.2](https://github.com/carpentries/styles/releases/tag/v9.5.2). Deployment progress tracked in carpentries/styles#302.
> Update to styles v9.5.2

- _episodes/14-writing-functions.md
The prior version used variables with capital letter labels which is distinctly not pythonic. Also, using `T` for the simulation time is not a particularly informative name.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the …
> adjust logistic_map example to be more pythonic

- reference.md
- needed for js / css asset requests to resolve properly
- fixes #334
This appears to be a different solution than that proposed in https://github.com/LibraryCarpentry/lc-data-intro/issues/49 (removing `permalink` and setting root to `.`). 
Could use some clarification into why this is needed for our lessons from a styles contributor..
> add root to yaml header

- _episodes/17-conditionals.md
Changed "...ones where the origina list's values were positive." to ""...ones where the original list's values were positive."
> Fixed typo in "Trimming Values" exercise

- CITATION
I believe the citation should include the maintainers.  Is the bi-annual DOI for each lesson still a feature?  This is probably something we should endeavor to get done by June.  Specifically, https://docs.carpentries.org/topic_folders/lesson_development/lesson_release.html
> include maintainers in this citation?

- _episodes/01-run-quit.md
This change moves the discussion of code vs. text cell types up to the first mention of cell types. I also added a very brief transitional sentence to introduce the word cell, since cells were previously referred to as blocks in the lesson.
This fixes #332, although I took a slightly different approach from the suggestion in that issue and moved the discussion up instead of down. I thought that it made the most sense to discuss cell types when the different types are first introduced.
> Moved discussion of cell types to introduction of cells

- _episodes/12-for-loops.md
Hello!
Explaining what a `for` loop is made of (in a language agnostic way) seems more important than Python's exact syntax for a `for` loop. This PR restructure episode 12 slightly so that the key point "A `for` loop is made up of a collection, a loop variable, and a body." comes before "The first line of the `for` loop must end with a colon, and the body must be indented."
If you agree with the intent of this PR, do you think "The first line of the `for` loop must end with a colon, and the body must be indented." should come even after the individual sections on variables, ranges, and loop bodies? Or is it best positioned where I've moved it for now?
Thanks for reviewing!
> Slightly restructure episode 12

- reference.md
When my changes were merged the page no longer had the section summaries at the top. I've fixed this, so the layout should be correct now.
> Layout correction to references

- _episodes/07-reading-tabular.md
Import Pandas using the common alias 'pd' and use the alias in the examples and exercises. Adds a sentence noting that this is a common alias.
> Import Pandas as pd in lesson 07

- _episodes/08-data-frames.md
> Import Pandas as pd in lesson 08, data frames

- _episodes/17-conditionals.md
> Import Pandas as pd in lesson 17, conditionals

- setup.md
change URL to gapminder wikipedia page for now due to possible clickjacking / embedded malware in their 404 page
> switch to wikipedia page for #419

- _episodes/01-run-quit.md
Changed instructions for launching Jupyter Lab on windows to specify Anaconda Prompt rather than CMD Prompt as per https://github.com/swcarpentry/python-novice-gapminder/issues/434
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort …
> Windows Anaconda Instructions

- _episodes/01-run-quit.md
Fixed typo: JupyerLab > JupyterLab
> Fixed typo: JupyerLab > JupyterLab

- _episodes/19-wrap.md
Is it likely that our learners want to see whichever questions were asked there recently? If not, please consider this update that sends them to the popular questions (which IMHO are likely more relevant and of exemplary quality).
> Show popular StackOverflow questions, not newest

- _config.yml
In case https://github.com/swcarpentry/python-novice-gapminder/commit/09550feeec221ad5027c7d5b9952fb7857c0777a included the `beta` setting _un_intentionally, please accept this PR. I'm guessing it was overlooked in #421's review, as this [lesson is listed as "core"](https://software-carpentry.org/lessons/) for a long time already ;-)
> Correct lifecycle metadata

- _episodes/09-plotting.md
Add comments to explain the str.strip() in the data.columns names prior to plotting from the dataframe (section 'Plot data directly from a Pandas dataframe')
The added comments should make it easier as the method strip() has not been introduced before in the material
> lesson09_update_comments_IIIcell

- _episodes/06-libraries.md
- _episodes/14-looping-data-sets.md
Hi,
I'm making a contribution for instructor training.
Issue #313 requested that the distinction between a "module" and a "library" be more consistent across episodes. After checking all instances of each term in the episode files, I believe there were only a couple instances that could use an update, which I've included. (I also added a stray missing "the").
Please let me know if you need any further changes to address the issue. 
Thanks!
> Consistent use of module and library

- reference.md
Small style changes of the references page to keep it inline with pep8 as we recommend there :wink:
> small style changes to references

- _episodes/01-run-quit.md
In the lesson 01-run-quit.md the expression dock panel
was being used once instead of main work area.
This PR is for issue #480.
> Change "dock panel" for "main work area"

- _episodes/03-types-conversion.md
- _episodes/06-libraries.md
- _episodes/11-lists.md
I found two broken links in the documentation. I tried to fix them by using `page.root` instead of the relative link. I checked it locally (after running make serve) and it seemed to work. Hopefully it also works for the Github pages.
> Fixed broken links to other episodes

- _episodes/09-plotting.md
viewed in the browser at http://swcarpentry.github.io/python-novice-gapminder/09-plotting/index.html, `g--` seems to be displaying as "g–" (see attached screenshot). This PR eliminates the potential confusion by wrapping the examples in the episode body in backticks, so that they are rendered on the page in monospaced font.
> monospace example line style arguments

- _episodes/03-types-conversion.md
Fixed the error in the floor division example. I have also added some text explaining why we need to subtract 1 first. This deals with #492.
> fix bug in floor division example, fixes #492

- _episodes/01-run-quit.md
Github's markdown parser gets confused because [some of the code fences inside div elements are not parsed as markdown](https://github.com/swcarpentry/python-novice-gapminder/blob/a2fbcf1c9e8aa0b770f93cd5012d9d4cfbd821ca/_episodes/01-run-quit.md#markdown-does-most-of-what-html-does)
This PR adds blank lines around div tags to avoid mistakes in parsing for markdown engines that are based on the [strict markdown spec for including HTML elements](https://daringfireball.net/projects/markdown/syntax#html) states:
> The only restrictions are that block-level HTML elements — e.g. `<div>, <table>, <pre>, <p>`, etc. — must be separated from surrounding content by blank lines
> Add space around <div> tags

- _extras/about.md
- _extras/design.md
- _extras/discuss.md
- _extras/exercises.md
- _extras/guide.md
- reference.md
- setup.md
See discussion here for more background: https://github.com/datacarpentry/datacarpentry.github.io/issues/542
In short, some Carpentries lessons use the path `/guide/` for their Instructor Notes page and others use `/guide/index.html` (the default defined in `_config.yml`). This PR removes permalinks with a trailing slash from the YAML front matter of the Instructor Notes (`_extras/guide.md`) and other Extras files, consistent with new lessons created with [the lesson template](https://github.com/carpentries/styles/). Although there's no functional difference in the online versions of the lesson pages, pages with a trailing slash in the permalink will result in **broken links in the version of the lesson built locally**. We'd like local builds to be usable e.g. in workshops taking place at …
> make lesson suitable for teaching with locally-built (serverless) pages

- _episodes/04-built-in.md
This PR addresses issue #115 . 
> In episode 4, "Every function returns something." might more naturally fit with the other points about functions, rather than following the section on help and debugging.
This PR:
* Moves "every function returns something" to directly after an example that uses print() to keep similar examples together
* Moves the Notebook help functions before the error messages
* Clarifies the text regarding Notebook help functions
> reorder 2 sections of the built-in function lesson

- _episodes/16-writing-functions.md
This PR is to address issues described in #461, which describes an exercise whose formatting could be improved.  While working on that exercise, I found a couple more with formatting oddities, so fixed them too.
* `Order of Operations`
* added numbering to match questions with solutions
* reordered the questions so that the function parse_dates() is introduced before it is asked about
* added a 3rd question about the `None` returned by parse_dates()
* removed the Python block formatting from `Calling by Name` because I think that section is part of the questions not part of the code
* added spaces to the items list in `Encapsulating Data Analysis` so the Markdown is parsed correctly
* `Encapsulate of If/Print Block`
* fixed typo in the title
* added and removed spaces from code examples …
> edits to standardize the format of exercises

- _episodes/09-plotting.md
Issue #482 requested a short note explaining plt.show() for users with other Python interpreters.  This PR:
- adds this note right below the first figure generated
- fixes some erroneous Python code block highlighting in the section `Adding a Legend`
> adding a note about plt.show()

- _episodes/16-writing-functions.md
When I submitted PR #514, I neglected to check the rendering of the exercises I had edited.  Turns out, I was missing some blank lines so the code blocks were all messed up.
While I was fixing that, I figured out how to intersperse code blocks with markdown lists so that the list items increment correctly (instead of resetting to 1 after the code block). This was a problem with another exercise, so I fixed that too.
The 2 exercises modified are "Order of Operations" and "Encapsulating Data Analysis"
> reformatting 2 exercises so they render correctly

- .gitignore
When serving the website of the lesson locally, Jekyll creates
a `.jekyll-cache` folder which shouldn't be pushed to the repository.
Would be better to tell `git` to ignore it so it never gets pushed by
accident.
For reference, the `.jekyll-cache` directory is already being ignored on
the [carpentries/lesson-example](https://github.com/carpentries/lesson-example) (see [bd56b2](https://github.com/carpentries/lesson-example/commit/bd56b2b083cb5929d603836e4024738cd5058ced)).
> Add .jekyll-cache to .gitignore

- _episodes/04-built-in.md
- _episodes/07-reading-tabular.md
- _episodes/08-data-frames.md
This PR is to address issue #473 which requests an introduction to methods be added before methods are used in the pandas episodes.  This PR:
* adds an example of methods using strings in Episode 4
* updates some text in Episode 7 - the first time I could find where a method is used
* changes the dir() exercise in Episode 8 (PR #341) to use strings instead of a list. This provides continuity and avoids using lists, which haven't been introduced yet.
I would like to add a couple changes to this PR, but I wanted to check first, because they aren't directly related. These are all in Episode 7
* ~~A reference to `math.pi` is made when introducing `DataFrame.columns`. I would remove that because I don't see any other references to `math`, which makes it confusing to me.~~  I just noticed the …
> Introducing methods in episode 4, and using them in episodes 7 and 8

- _episodes/04-built-in.md
Without any text in the first bullet point, the list is rendered incorrectly:
This PR adds minimal amount of text to fix this:
> 04-built-in.md: fix nested Markdown list

- _episodes/07-reading-tabular.md
Without indentation, both list items appear with index 1:
<details><summary>Screenshot</summary>
</details>
> 07-reading-tabular.md: fix indentation in 'Inspecting Data'

- _episodes/03-types-conversion.md
The modulo operator `%` was rendered differently than `/` and `//`.
> Fix formatting typo

- _episodes/18-style.md
ops! this changes the URL to the tool mentioned, tha was renamed
pep8 -> pycodestyle
> pep8 tool was renamed as pycodestyle

- _episodes/04-built-in.md
Hi,
This PR adds a callout block to the end of the episode that links to the Python documentation.
There are other mentions of the Python docs throughout the lesson, but I considered that the Built-in Functions topic would be a good place to insert a more complete reference to the docs page. I hope this change is helpful to the lesson.
Best,
Vini
> Add callout block referring to Python docs

- _episodes/06-libraries.md
`randint` and `randrange` are different methods/functions, so I propose to remove the part that says that one is an alias for another.
> 06-libraries.md: randint vs. randrange

- _episodes/09-plotting.md
Running `%matplotlib inline` is no longer necessary when we want to directly display figures in a Jupyter notebook. This has been the default behaviour of Jupyter for several years, since a few versions ago.
There are no mentions of "magic" commands elsewhere in this lesson, so I feel it would be quite confusing if not properly explained, and would be a loss of time if explained in detail (since I would also argue that these later episodes should be more about python than about IPython).
> Remove matplotlib inline magic

- _includes/python_install.html
- assets/css/lesson.scss
- setup.md
Hi,
Please see #501 for discussion.
If merged, this PR will:
- Add the `_includes/python_install.html` file with setup instructions, the same present in [carpentries/workshop-template](https://github.com/carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/python.html) repository. This file contains embedded video instructions for each operating system.
- Include said file in the `setup.md` (and delete previous instructions). I also moved the "Getting the Data Section" up so it does not stay hidden below the Python setup section.
- Update the `assets/css/lesson.scss` file according to the [carpentries/workshop-template](https://github.com/carpentries/workshop-template/blob/gh-pages/assets/css/lesson.scss) repository.
I do know that altering static files may be a bit …
> setup.md: Update Python installation instructions

- _episodes/16-writing-functions.md
As noted in #538, the function `print_date` was previously used in the episode, leading to a student to potentially fail to experience the expected error if they type the code into their current python session.
This updated question will use `print_time` instead. This is a very simple substitution which I should be as accessible as  `print_date`.
> Replace print_date function in episode 16 question

- _includes/python_install.html
Issue 397 explains how Jupyter Notebook was replaced with JupyterLab throughout this lesson. The setup page was not updated. https://github.com/swcarpentry/python-novice-gapminder/issues/397
I've made some suggestions here including links to docs. Please check them carefully, I'm not sure if these changes are correct or necessary.
Perhaps the docs links should go to 'stable' rather than 'latest' in my code suggestion?
> Replace Jupyter Notebook with JupyterLab in Setup page

- _episodes/08-data-frames.md
This is an improvement based on the suggestions from #532.
I added a Challenge asking learners to suggest different ways of doing access operations on a DataFrame. I used the notes from #532 as answer to the Challenge.
Thank you for any assistance or feedback you can provide.
Best,
V
> Episode 8: Add 'Many Ways of Access' challenge.

- _episodes/16-writing-functions.md
Some Python code snippets in episode 16 are exhibiting odd indentation levels (1, 3, 5 spaces). This pull request restores the originally intended indentation (multiples of 4 spaces).
> Clean indentation in 16-writing-functions

- _episodes/16-writing-functions.md
In episode 16, the panel "Encapsulation of an If/Print Block" asks the learner to turn the if-block into a function a total of three times:
- "Please re-write the code so that the if-block is folded into a function."
- "What function definition will make it functional?"
- "Create a function definition..."
Only the last of these is needed. The first one is particularly unhelpful as it comes before the task is properly defined.
This pull request removes the duplication, and instead provides a potential rationale for wanting to do the task in the first place. (It also removes some trailing spaces.)
> Avoid setting encapsulation challenge too early

- _episodes/11-lists.md
The solution for "How Large is a Slice?" says the the expression `values[low:high]`, or possibly `high - low`, will only work if `high` is less than the total length of the list `values`. This isn't quite correct on either interpretation.
As shown in Episode 2, `values[low:high]` will always return a list, even if one or both of the limits are out of bounds. The length of the slice will be `high - low` if and only if `high` is equal to or less than the length of the list; it will be zero if both `high` and `low` are greater than the length of the list, and somewhere in between otherwise.
This pull request suggests alternative wording that I think would be clearer and more accurate.
> Clarify explanation of "How Large is a Slice?"

- _episodes/14-looping-data-sets.md
The solution to "Minimum File Size" in Episode 14 includes a use of `float('Inf')`; this is not introduced previously and might well come as a surprise.
For the benefit of those learners who went for `1e10` or similar, this PR cushions the blow a bit by explaining that, while using a big enough number is valid, using infinity is better. It then provides a link to the documentation that explains about this and other special strings that can be passed to `float()`.
> Provide link to documentation of float('Inf')

- _episodes/16-writing-functions.md
The challenge "Simulating a dynamical system" in Episode 16 asks for values at times `[0,1,...,t_final]` but the solutions provide values at times `[0,1,...,t_final - 1]`.
For example, in part two of the solution, `population` is initialized with the `initial_population`, and then the loop runs 9 times (`range(1, 10)`) to give a total of ten values, the last of which is the value at *t* = 9. A tenth run is needed to get what was asked for, so the loop should be:
```python
for t in range(t_final):
population.append( logistic_map(population[t], r) )
```
Happily, this looks even more like the function in part one, where you get the value at *t* + 1 in terms of the value at *t*, rather than the value at *t* in terms of the value at *t* - 1.
This PR supplies the corrected code for parts two …
> Correct solutions for "Simulating a dynamical system" (Ep. 16)

- _episodes/12-for-loops.md
- _episodes/18-style.md
Resolves #582 per issue discussion.
I did leave one instance of += in the exercise in episode 18, since its point was to emphasize the value of readable rather than terse code and I feel that running into unfamiliar syntax in the wild is a pretty common experience with codebases that need refactoring. Happy to remove it for overall consistency, though.
> Remove unexplained augmented assignment operators from examples

- _includes/links.md
Repeated link to jupyter.org for JupyterLab in links.md to address #594. This PR is a copy of #595, but from a new branch.
> Fix JupyterLab link in index.md

- _episodes/09-plotting.md
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
---
Swap the order of lines 327 (fig = plt.gcf() # get current figure) and 328 (data.plot(kind='bar'). This will then correctly save the bar plot as the last global plot. Currently, this code does not save and generates an empty plot file.
> Change order of line 327 and 328 - Lesson Contribution

- _episodes/09-plotting.md
`str.strip()` actually removes each character in the character class string. So `.strip('gpdaPerc_')` would also do the same thing and is confusing.  I made a live typo during the workshop and a student asked me how was it that it still worked when I had typed `gdp_Percap_` even though there's no `_` between `gdp` and `Per`!
Reference: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html and https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html
> replace `str.strip()` with `str.replace()`

- _episodes/07-reading-tabular.md
Updated lesson to use dataframe names following a similar standard convention (data_[region]_[indexColumn]) throughout and added bullets pointing out the advantages.
These changes should be consistent across all episodes to demonstrate preferred naming conventions.  Previously dataframes were overwritten and less clearly distinguishable (e.g. `data`).
refs #628
> improve dataframe naming conventions

- episodes/08-data-frames.md
- episodes/16-writing-functions.md
Fix #628 
Episode 8:
- Renamed `df` to `europe`
Episode 16:
- Renamed `df` to `asia` for the first specific case
- Renamed `df` to `countries` in the function writing exercise, since the generic `continent` is already used
> 628 explicit df names

- learners/setup.md
To reduce confusion for learners visiting the installation instructions, this links to a dedicated page of installation instructions in the template workshop website. This is instead of the template landing page, which contains a lot of FIXMEs that can be alarming and give someone the impression that the link has taken them to the wrong place.
> link to dedicated installation instructions page in workshop template

- episodes/18-style.md
This is meant to fix #464 but I'd love some feedback on how to succinctly describe the difference in use between comments and docstrings.
> Comments vs docstrings

- learners/reference.md
> fix: remove leftover jekyll `auto_ids` directive

- episodes/13-conditionals.md
Example was written in the wrong order. I adjusted the grade A for the grade C
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions …
> Update 13-conditionals.md: fixed example

- episodes/14-looping-data-sets.md
pandas now raises errors when computing the mean on a dataframe with non-numeric columns
add a note to the challenge describing the issue and provide a few additional ways of solving it
Thanks to @davidwilby for finding this bug and outlining possible solutions to it in #670
> fix: clarify pandas usage with non-numeric columns

- README.md
The link in README still refers to the old docs for the lesson template. I have updated it to link to the Workbench docs.
> Workbench link in Readme

- episodes/01-run-quit.md
cherry picking work from @martinosorb in #677 
Context from that PR:
> This is apparently needed for the lesson to be workable with Crowdin for internationalisation purposes (see [this thread on Slack](https://carpentries.slack.com/archives/CL357S0CD/p1708392714885819?thread_ts=1706754620.155089&cid=CL357S0CD)).
> 
> Please note that I can't, at the moment, check whether the version in this PR will actually work in Crowdin -- but the problem there is supposed to be about the use of \<div\>.
> 
> What the PR does is to change the [section on Markdown](http://swcarpentry.github.io/python-novice-gapminder/01-run-quit.html#the-notebook-has-command-and-edit-modes.) of the first episode to look like this:
> ![image](https://github.com/swcarpentry/python-novice-gapminder/assets/11293950/8ed7c87a- …
> convert divs into table

- episodes/16-writing-functions.md
Simulating a dynamical system solution had a new line in the code block which caused the whole block not to be rendered.
URL: https://swcarpentry.github.io/python-novice-gapminder/16-writing-functions.html
Before and after screenshots below:
After:
> Improve formatting of episode 16 solution

- episodes/09-plotting.md
Corrects three occurrences of lower case "gdp" on the page on [plotting](https://swcarpentry.github.io/python-novice-gapminder/instructor/09-plotting.html), including one typo ("gdb"). 
The rest of the page consistenly uses capital GDP.
> Three "gdp" -> "GDP" on Plotting page

- episodes/14-looping-data-sets.md
Issue #673
Extract the years from the columns (so instead of `gdpPercap_<year>` will just be the year), and add title to the plot as `GDP Per Capita for Regions Over Time`.
> Issue 673: Add title and just year as x-axis label

- profiles/learner-profiles.md
Closes #664.
Based on issue #664, I'm adding some learner profiles for the course in place of the current (empty) placeholder.
This is my first time writing these sort of profiles, so I'd be happy for suggestions on improvements. I took these as inspirations:
- https://carpentries-incubator.github.io/python-packaging-publishing/learner-profiles/index.html
- https://github.com/carpentries-incubator/hpc-intro/blob/gh-pages/_extras/learner-profiles.md
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to …
> Add first draft of learner-profiles

- episodes/04-built-in.md
_[This repeats the changes made in #695 (then reverted in #696). I am sorry for the confusion! 😅 The pull request will stay open for at least a week, to give community members time to provide feedback and suggest improvements. Thanks for your patience @vahtras and other Maintainers ❤️ ]_
This adds a new section to _Built-in Functions and Help_, titled "Other ways to get help" that discusses searching the internet, StackOverflow, talking to another person, and generative AI chatbots e.g. ChatGPT as possible ways to get more help when faced with errors while coding.
Some notes to guide feedback:
* I have tried to keep this as concise as possible, sticking to what I consider to be the most essential information only. But concede that it is still pretty wordy!
* These changes are guided by …
> (Re-)Add content on generative AI
